# STAT 207 Lab Assignment 2 - Individual Part - [25 total points]

## Dataframe Manipulation and Cleaning

Due: Tuesday, January 30, 11:59pm CST

<hr>


## <u>Case Study</u>: Steam Game Play and Purchase Analysis
Steam is the world's most popular PC Gaming hub. With a massive collection that includes everything from AAA blockbusters to small indie titles, great discovery tools can be super valuable for Steam. We would like to use the following dataset below to learn more about Steam player behavior.

The dataset we will be analyzing is comprised of a random sample of 400 steam users and their game play and purchase behaviors. It has the following columns:
* **user_id** of the player
* **game_name**,
* **activity**:
    - <u>purchase</u>: indicating that the user has *purchased* the corresponding game
    - <u>play</u>: indicating that the user has *played* the corresponding game (for at least some amount of time.) 
* **hours_played_if_play**:
    - if the row corresponds to a 'play' activity, this number represents the number of hours the user has played the game
    - if the row corresponds to a 'purchase' activity, this number is always a 1 (and means nothing... it's a placeholder).

<hr>


### <u>Research Goals</u>

In this analysis, we will consider a game's **"all-star" player** to be the person who had played this game for the most amount of hours. With this definition in mind, we will do the following in this assignment.

1. **Missing Value Cleaning**: Identify any implicit or explicit missing values in the dataset and drop any rows that have a missing value.
2. **Game Purchase vs. Play Behaviors**: What percent of games that were *bought* were actually *played* in this dataset?
3. **Top Game Buyer**: Learn more about the person who bought the most amount of games in this dataset. How many of these games did they actually play?
4. **"All Star Players"**: Who were the "all-star players" of the games? How long did they play this game?
5. **All Star Player Behavior**: What percent of games that these "all star players" bought did they actually play?



### <u>Points </u>
<p style="margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:11.0pt;font-family:&quot;Calibri&quot;,sans-serif;line-height:normal;"></p>
<table style="border: none;border-collapse: collapse;width:102pt;">
    <tbody>
        <tr>
            <td style="color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;width:51pt;">Problem</td>
            <td style="color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-left:none;width:51pt;">Points</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">3</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">6</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">4</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">1</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">5</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">6</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">7.1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">7.2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">8.1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">8.2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">8.3</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">1</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">8.4</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">2</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">9</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">1.5</td>
        </tr>
    </tbody>
</table>
<p></p>




<hr>

### <u>STAT107 Review</u>
Part of this individual assignment will involve a review of STAT107 code that you have seen before including the following. Click on the links below if you need a refresher.

1. <a href="https://discovery.cs.illinois.edu/learn/Basics-of-Data-Science-with-Python/DataFrames-with-Conditionals/">Row Filtering</a>
2. <a href="https://discovery.cs.illinois.edu/guides/Modifying-DataFrames/dataframe-groupby/">The groupby() and reset_index() Functions</a>
2. <a href="https://discovery.cs.illinois.edu/guides/Modifying-DataFrames/sorting-a-dataframe-with-pandas/">The sort_values() Function</a>


### <u>Tutorial you Will Need</u>: Utilizing the *.shape* attribute

The **.shape** attribute for a given dataframe returns a **tuple** of two values, the first value in the tuple is the number of rows, the second value is the number of columns.

In [1]:
import pandas as pd
demo_df=pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
demo_df

a  b
0  1  4
1  2  5
2  3  6

We can index a tuple with 0 and 1 indices to extract the number of rows and columns from the dataframe separately.

In [2]:
#Number of rows and columns
demo_df.shape

(3, 2)

In [3]:
#Number of rows
demo_df.shape[0]

3

In [4]:
#Number of columns
demo_df.shape[1]

2

<hr>

### Imports

In [34]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### 1. Read the csv
First, read the **steam_sample_400.csv** file into a dataframe and display the first five rows of the dataframe.

In [6]:
df = pd.read_csv("steam_sample_400.csv")
df

user_id                                     game_name  activity  \
0     218323237                                        Dota 2  purchase   
1     218323237                                        Dota 2      play   
2     218323237                                   Tomb Raider  purchase   
3     218323237                                   Tomb Raider      play   
4     218323237                                          TERA  purchase   
...         ...                                           ...       ...   
6302    7519923                                Counter-Strike      play   
6303    7519923                 Counter-Strike Condition Zero  purchase   
6304    7519923  Counter-Strike Condition Zero Deleted Scenes  purchase   
6305  103963922                               Team Fortress 2  purchase   
6306  103963922                               Team Fortress 2      play   

     hours_played_if_play  
0                       1  
1                    14.8  
2                       1  
3                     8.8  
4                       1  
...                   ...  
6302                   35  
6303                    1  
6304                    1  
6305                    1  
6306                  0.4  

[6307 rows x 4 columns]

### 2. How many rows does the dataframe have? (Use Python code to show this).

In [7]:
df.shape[0]

6307

### 3. Data cleaning and data type checking

We plan to analyze the **"hours_played_if_play"** variable in this assignment. In order to ensure that our subsequent functions work appropriately on this numerical variable, you should do the following.
1. Identify any values (if any) that have been encoded in the csv to represent a **missing value**. 
2. Make sure that the values in your **"hours_played_if_play"** variable are represented as numerical values (either float64 or int64 object types). If not, fix this using the methods we discussed in class.
3. PERMANENTLY delete any rows in your dataframe that have missing values (both explicit or implict). Remember, some "missing values", in the way that they're currently encoded in the csv may not be initially detectable by Python. It is your job to figure out what these implicit missing values are and make it so Python does detect them. And then delete any rows that have them.

In [28]:
df.isna().sum()

# there are no NaN values

user_id                 0
game_name               0
activity                0
hours_played_if_play    0
dtype: int64

In [29]:
df.dtypes

# hours_played_if_play is not exclusively numerical

user_id                  int64
game_name               object
activity                object
hours_played_if_play    object
dtype: object

In [33]:
np.unique(df["hours_played_if_play"].values)

# found "data missing" and "data not found"

array(['0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '1',
       '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9',
       '10', '10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7',
       '10.8', '10.9', '1009', '101', '1015', '102', '1024', '1026',
       '1029', '103', '105', '1054', '106', '107', '109', '11', '11.1',
       '11.2', '11.3', '11.4', '11.6', '11.7', '11.8', '11.9', '110',
       '111', '1113', '1118', '112', '114', '1149', '116', '117', '119',
       '1195', '12', '12.1', '12.2', '12.3', '12.4', '12.5', '12.6',
       '12.7', '12.8', '12.9', '120', '121', '122', '123', '1231', '1243',
       '125', '1250', '126', '127', '128', '1298', '13', '13.1', '13.2',
       '13.3', '13.4', '13.5', '13.6', '13.8', '13.9', '131', '1319',
       '132', '1322', '133', '134', '136', '137', '138', '1395', '14',
       '14.1', '14.2', '14.3', '14.4', '14.5', '14.6', '14.7', '14.8',
       '14.9', '140', '141', '142', '145', '146', '1467', '1478', '148',


In [36]:
df2 = pd.read_csv("steam_sample_400.csv", na_values=["data missing", "data not found"])

# re-load the csv file with custom na values

In [38]:
df2.dtypes

# hours_played_if_play is now of type float64

user_id                   int64
game_name                object
activity                 object
hours_played_if_play    float64
dtype: object

In [40]:
df2.isna().sum()

# there are 9 na values in hours_played_if_play

user_id                 0
game_name               0
activity                0
hours_played_if_play    9
dtype: int64

In [44]:
df3 = df2.dropna()
df3.isna().sum()

# remove all na rows

user_id                 0
game_name               0
activity                0
hours_played_if_play    0
dtype: int64

### 4. Number of Dropped Rows 

How many rows with missing values did you delete from your original dataframe?

In [46]:
df2.isna().sum()

# 9 rows were removed

user_id                 0
game_name               0
activity                0
hours_played_if_play    9
dtype: int64

### 5. Separate the dataframes. 

Next, in this analysis we would like to analyze the game purchase information and game play information separately. First create two new dataframes:
* one that is comprised of the purchase rows
* the other that is comprised of the play rows.

In [47]:
df_play = df3[df3["activity"] == "play"]

In [48]:
df_purchase = df3[df3["activity"] == "purchase"]

### 6. Percentage of Game Purchases that are Actually Played

What percentage of all total game purchases in this dataset are actually played by the player that purchased them?

*You can assume that a game and user id that has a 'play' row ALSO MUST have a 'purchase' row (but not the other way around).*

**For full credit, use automated Python code to find your answer. (Ie. don't put something like '30/50', where you found the 30 and 50 from the output of other code.)**

In [65]:
len(df_play) / len(df_purchase)

0.5808232931726908

### 7. Top Game Purchaser

Next, we'd like to learn more about the people who *purchase* the most amount of games.

#### 7.1. Most Amount of Games Purchased

What is the user id of the player who has purchased the most amount of games in this dataset, and how many games have they purchased?

In [69]:
df_purchase.groupby("user_id").agg("count").nlargest(1, "activity")

game_name  activity  hours_played_if_play
user_id                                            
27279261        185       185                   185

User 27279261 has purchased the most games; they have purchased 185 games.

#### 7.2. How many games has this user actually played?

What percentage of the purchased games did this player from 7.1 actually play?

In [76]:
df_play.groupby("user_id").get_group(27279261)["activity"].agg("count") / 185

0.5567567567567567

## 8. Examining Some Game "All-Star" Players

Next, we'd like to examine the play vs. purchase behavior of a few games' "all star players". We will consider a game's "all star player" to be the one who has played the game the longest in this dataset.

### 8.1. Each Game's Highest Play Time

In a single dataframe below, display the highest amount of time that each game was played.

For full credit, your final resulting dataframe should:
1. Be comprised of *two columns*
 * `game_name`
 * `hours_played_if_play`
2. And should have an index going from 0,1,2,... etc.

In [93]:
df_gametime = df3[["game_name", "hours_played_if_play"]].groupby("game_name").agg("sum").reset_index()
df_gametime

game_name  hours_played_if_play
0                 100% Orange Juice                   1.0
1                     7 Days to Die                 541.2
2                           8BitBoy                  26.2
3             A Valley Without Wind                   2.2
4           A Valley Without Wind 2                   1.1
...                             ...                   ...
1330              how do you Do It?                   1.0
1331   realMyst Masterpiece Edition                   8.5
1332  resident evil 4 / biohazard 4                   4.8
1333                   sZone-Online                   1.0
1334                      theHunter                   6.8

[1335 rows x 2 columns]

### 8.2. Ranking the Games by Highest Maximum Game Play Time

Sort your final resulting dataframe from 8.1 by the number of hours that the game was played by the all-star player *in descending order*.

Overwrite your dataframe, so it remains sorted in this order.

In [98]:
df_gametime = df_gametime.sort_values("hours_played_if_play", ascending=False)
df_gametime

game_name  hours_played_if_play
341                              Dota 2               51674.2
245     Counter-Strike Global Offensive               11066.9
983          Sid Meier's Civilization V                7492.2
242                      Counter-Strike                6744.4
87    Baldur's Gate II Enhanced Edition                3900.0
...                                 ...                   ...
471                           From Dust                   1.0
473                                GRID                   1.0
475              GRID 2 GTR Racing Pack                   1.0
1045         State of Decay - Breakdown                   1.0
0                     100% Orange Juice                   1.0

[1335 rows x 2 columns]

### 8.3. Top 3 Games with the Most Dedicated "All-Star Player"

Which three games in this dataset had the most "dedicated" "all star players"? Or in other words, which three games were played the longest amount of time by a particular player?

In [104]:
# df_play.sort_values("hours_played_if_play", ascending=False)
df_play.groupby("game_name").agg("max").sort_values("hours_played_if_play", ascending=False)

user_id activity  hours_played_if_play
game_name                                                                   
Dota 2                              309824202     play                5608.0
Sid Meier's Civilization V          281535206     play                5002.0
Baldur's Gate II Enhanced Edition    52731290     play                3898.0
Baldur's Gate Enhanced Edition       52731290     play                2630.0
Counter-Strike                      211197762     play                2526.0
...                                       ...      ...                   ...
DOOM 3 BFG Edition                    9180659     play                   0.1
Indie Game The Movie                134322141     play                   0.1
I Have No Mouth, and I Must Scream   65145468     play                   0.1
A Valley Without Wind 2              71527252     play                   0.1
SkyDrift                            107743243     play                   0.1

[843 rows x 3 columns]

This question seems ambiguous, I can think of two separate interpretations. I've given both above and left the one I think makes more sense uncommented. The three *unique* games played the longest time by a *particular* player are Dota 2, Sid Meier's Civilization V, and Baldur's Gate II Enhanced Edition.

Using the other iterpretation I listed above, the three games with the longest time by a particular player would be Dota 2, Sid Meier's Civilization V, and Dota 2 *again*

### 8.4. Identifying these "All Star Players"

For these three games that you selected in 8.3 above, what is the user id of their respective "all star player"?

## 9. Learning about the All-Star Players

Finally, let's learn more about the play vs. purchase behavior of these three "all star" players that we identified in #8. Specifically for each of these three player user ids that you identified in #8, what percentage of games that they bought did they actually play?